# Values formatted like "_env:YESOD_ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:YESOD_STATIC_DIR:static"
host:           "_env:YESOD_HOST:*4" # any IPv4 host
port:           "_env:YESOD_PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
ip-from-header: "_env:YESOD_IP_FROM_HEADER:false"

# Default behavior: determine the application root from the request headers.
# Uncomment to set an explicit approot
#approot:        "_env:YESOD_APPROOT:https://feio.herokuapp.com/"
#approot:        "_env:YESOD_APPROOT:http://localhost:3000"

# By default, `yesod devel` runs in development, and built executables use
# production settings (see below). To override this, use the following:
#
# development: false

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false
# auth-dummy-login : false

# NB: If you need a numeric value (e.g. 123) to parse as a String, wrap it in single quotes (e.g. "_env:YESOD_PGPASS:'123'")
# See https://github.com/yesodweb/yesod/wiki/Configuration#parsing-numeric-values-as-strings

#database:
#  user:     "_env:YESOD_PGUSER:feio"
#  password: "_env:YESOD_PGPASS:feio"
#  host:     "_env:YESOD_PGHOST:localhost"
#  port:     "_env:YESOD_PGPORT:5432"
  # See config/test-settings.yml for an override during tests
#  database: "_env:YESOD_PGDATABASE:feio"
#  poolsize: "_env:YESOD_PGPOOLSIZE:10"

database:
  user:     "_env:YESOD_PGUSER:cchnytkxhjfwgz"
  password: "_env:YESOD_PGPASS:7215cddee575aca243f2033f0240748fc6af898b0038f842cb8025e915166ef7"
  host:     "_env:YESOD_PGHOST:ec2-35-174-127-63.compute-1.amazonaws.com"
  port:     "_env:YESOD_PGPORT:5432"
  # See config/test-settings.yml for an override during tests
  database: "_env:YESOD_PGDATABASE:dacnbp301aob2i"
  poolsize: "_env:YESOD_PGPOOLSIZE:10"




copyright: Insert copyright statement here
#analytics: UA-YOURCODE
